# fly.toml app configuration file generated for cloud-torrent on 2025-07-15T06:13:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cloud-torrent'
primary_region = 'sin'

[build]
  dockerfile = '.github/Dockerfile'
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "cloud-torrent"
  destination = "/downloads"
  processes = ["disk"] # optional - attach volumes to Machines that belong to one or more process groups
  initial_size = "20gb" # optional - the size of the volume created on first deploy

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
